export const SITE_CONFIG = {
  name: "Sudip Chaudhary",
  title: "SEO Expert Nepal | Best SEO Agency Kathmandu | Sudip Chaudhary",
  description: "Best SEO expert in Nepal and Kathmandu. Specializing in technical SEO, content strategy, and helping Nepali businesses rank higher on Google. Proven results from experienced SEO specialist.",
  url: "https://sudipchaudhary101.com.np",
  ogImage: "https://sudipchaudhary101.com.np/og-image.png",
  email: "chsudip28@gmail.com",
  social: {
    github: "https://github.com/sudipchaudhary30",
    linkedin: "https://www.linkedin.com/in/sudip-chaudhary",
    twitter: "https://twitter.com/sudipchaudhary",
  },
  author: "Sudip Chaudhary",
  locale: "en_NP",
  location: "Kathmandu, Nepal",
  keywords: [
    "SEO expert Nepal",
    "SEO expert Kathmandu",
    "Best SEO agency in Nepal",
    "best SEO agency Nepal",
    "Best Digital Marketing Agency in Nepal",
    "SEO specialist Nepal",
    "SEO services Kathmandu",
    "technical SEO Nepal",
    "local SEO Kathmandu",
    "SEO consultant Kathmandu",
    "Nepali SEO expert",
    "top SEO agency Kathmandu",
    "search engine optimization Nepal",
    "SEO services Nepal",
    "professional SEO Kathmandu"
  ]
} as const;

export const projects = [
  {
    id: 1,
    title: "Nepal E-Commerce: Page 5 to Page 1 in 6 Months",
    description: "Helped a Kathmandu-based e-commerce business rank on the first page for competitive Nepali keywords through technical SEO and content strategy.",
    technologies: ["Technical SEO", "Schema Markup", "Content Strategy", "Link Building"],
    metrics: "+320% organic traffic, NPR 6L+ revenue from organic",
    link: "#",
  },
  {
    id: 2,
    title: "Local SEO for Kathmandu Service Business",
    description: "Optimized Google Business Profile and local citations for a service provider in Kathmandu. Now ranks in the top 3 for local searches.",
    technologies: ["Local SEO", "GMB Optimization", "Citation Building", "Review Management"],
    metrics: "+150% local visibility, Top 3 for 15+ local keywords",
    link: "#",
  },
  {
    id: 3,
    title: "Nepal Multi-City SEO Strategy",
    description: "Developed location-based SEO strategy for a services company targeting Kathmandu, Pokhara, Lalitpur, and Biratnagar.",
    technologies: ["Local SEO", "Location Pages", "hreflang", "Schema Markup"],
    metrics: "+200% visibility across cities, +4 new locations ranking",
    link: "#",
  },
  {
    id: 4,
    title: "Nepal SaaS Company Content Strategy",
    description: "Built comprehensive content strategy and blog for a Nepal SaaS company targeting Nepali business owners.",
    technologies: ["Content Strategy", "Keyword Research", "SEO Writing", "Internal Linking"],
    metrics: "+250% organic traffic, +180 qualified leads monthly",
    link: "#",
  },
  {
    id: 5,
    title: "B2B Services: Technical SEO Overhaul",
    description: "Complete technical SEO audit and implementation for a B2B services company in Nepal fixing Core Web Vitals and site structure.",
    technologies: ["Technical SEO", "Core Web Vitals", "Schema Markup", "Site Architecture"],
    metrics: "+400% page 1 keywords, 60% improvement in page speed",
    link: "#",
  },
  {
    id: 6,
    title: "Real Estate Portal: SEO to 10k Monthly Visits",
    description: "Implemented comprehensive SEO strategy for a Nepal real estate platform targeting local property searches.",
    technologies: ["Technical SEO", "Local SEO", "Content Strategy", "Link Building"],
    metrics: "10k+ monthly organic visits, +500 keyword rankings page 1",
    link: "#",
  },
];